title: Samuel Adeagbo
logo: Headshot.jpg
description: Passionate about turning raw data into actionable insights. With over two experienced in data analysis, visualization, and reporting to drive business decisions. Proficient in SQL, Power BI, Tableau, Python, and Excel, with expertise in database querying, statistical analysis, and dashboard development.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
