title: Samuel Adeagbo
logo: Headshot.jpg
description: 📊 Data Analyst | SQL | Power BI | Tableau | Python | Excel

Passionate about turning raw data into actionable insights. With over two experienced in data analysis, visualization, and reporting to drive business decisions. Proficient in SQL, Power BI, Tableau, Python, and Excel, with expertise in database querying, statistical analysis, and dashboard development.

🚀 Always exploring data-driven solutions!

🔗 Check out my projects below! 👇
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
